name: tiamat10-test
recipe: lamp 
tooling:
  drush:
    description: Run drush commands
    service: appserver
    cmd: "/app/vendor/bin/drush --root=/app"
  install-site:
    description: Install Drupal 10 site with the CU Boulder Profile
    service: appserver
    cmd: >
      echo yes | /app/vendor/bin/drush si boulder_profile
      --db-url="mysql://lamp:lamp@database:3306/lamp"
      --site-name="Web Express D10 Test Site"
      --account-name="admin" --account-pass="tiamat.test"
      install_configure_form.enable_update_status_module=NULL
      install_configure_form.enable_update_status_emails=NULL &&
      /app/vendor/bin/drush pmu simplesamlphp_auth &&
      echo "\nLogin with Username: admin Password: tiamat.test" &&
      php -r "echo 'Site URL: ' . json_decode(getenv('LANDO_INFO'), TRUE)['appserver']['urls'][0];" &&
      echo "\n"
  nosso:
    description: Uninstall simpleSAMLphp_auth module to allow local authentication
    service: appserver
    cmd: "/app/vendor/bin/drush pmu simplesamlphp_auth"
  behat:
    description: Run Behat Tests
    service: appserver
    cmd: "/app/vendor/bin/behat -c behat.local.yml"
  phpunit:
    description: Run Unit Tests with phpunit
    service: appserver
    cmd: "/app/vendor/bin/phpunit -c phpunit.local.xml --debug"
services:
  appserver:
    build:
      - composer install
config:
  php: '8.3'
  composer_version: '2.7.9'
  webroot: web
  database: mariadb
  xdebug: false
